mie-lab/trackintel

.gitignore
Pipfile

Make sure that development packages are installed and Pipfile.lock is ignored.

build(pipenv): install package in editable mode

---

tests/test_io.py
trackintel/preprocessing/triplegs.py

added tripleg smoothing with Douglas Peucker

Douglas-Peucker

---

environment.yml
requirements.txt
tests/preprocessing/test_preprocessing.py
tests/test_io.py
tests/test_model.py
trackintel/preprocessing/staypoints.py

File triplegs_with_too_many_points_test.csv is missing. The tests for douglas-peucker are commented out.

update tests and minor bugfix such that test are passing. 

---

.travis.yml
setup.py

The simplification library had to be added to setup.py and requirements.txt

Repair travis

---

tests/test_distances.py

test for the haversine-distance

Add test_distances.py

---

.github/workflows/rstcheck.yml

This PR adds a github action that runs rstcheck on each PR or push to the repository. 
rstcheck is a tool to ["Checks syntax of reStructuredText and code blocks nested within it."](https://pypi.org/project/rstcheck/)

Add github action to check documentation syntax

---

tests/preprocessing/test_triplegs.py
trackintel/preprocessing/triplegs.py

- replaced the simplify function in simplification.cutil to the one in shapely
- modified the test function

douglas peucker function and test

---

docs/tutorial.rst
trackintel/preprocessing/positionfixes.py

Proposing a simple fix for the issue below
[issue #74](https://github.com/mie-lab/trackintel/issues/74#issue-757852729)

Fixing issue #74

---

.github/workflows/python-package.yml
ci/envs/37-latest-conda-forge.yaml
ci/envs/38-latest-conda-forge.yaml
ci/envs/39-latest-conda-forge.yaml
ci/envs/setup_postgres.sh
environment.yml
tests/io/test_postgis_gpd.py
tests/preprocessing/test_triplegs.py
tests/test_visualization.py
trackintel/io/dataset_reader.py

Continuous integration for postgis, different python versions and different OS
I adjusted the continuous integration setup from geopandas to set up continuous integration for postgis. On my way I could also already identify some (minor) OS specific bugs.
At the moment I am not sure how this goes along with the test coverage that we have set up. We could think about copying the setup from geopandas for that as well.

Continuous integration for PostGIS

---

.github/workflows/auto_update.yml

workflow updates pending pull requests if the branch gets updated

feat: autoupdate workflow

---

tests/io/test_file.py
tests/io/test_from_geopandas.py
tests/preprocessing/test_staypoints.py
tests/preprocessing/test_triplegs.py
trackintel/io/dataset_reader.py
trackintel/io/file.py
trackintel/model/tours.py

- add function signatures for tour io
- changed the wording and suppress warning for tests
No change of functions. Can be merged once the tests are passed.

Add function signatures for tour io

---

CONTRIBUTING.md
docs/conf.py
trackintel/__version__.py

update the version number to 0.5.0 for new pypi release

update version number for new release

---

docs/modules/io.rst
trackintel/io/file.py
trackintel/io/from_geopandas.py

-included io.from_geopandas in documentation
-cleanup / bugfixes in io documentation

DOC: Added Geopandas import functions to documentation + cleanup

---

trackintel/model/tours.py
trackintel/model/trips.py

BUG: Corrected wrong error message in trips accessor. #122

---

tests/io/test_file.py
trackintel/io/file.py

ENH: Added option to set CRS in read_xx_csv function #123

---

CONTRIBUTING.md

DOC: Added convention for trackintel datatypes

---

tests/test_visualization.py
tests/visualization/test_util.py
trackintel/visualization/locations.py
trackintel/visualization/positionfixes.py
trackintel/visualization/staypoints.py
trackintel/visualization/triplegs.py
trackintel/visualization/util.py

ENH: Added function for transforming into WGS84.

---

docs/modules/analysis.rst
tests/analysis/test_tracking_quality.py
trackintel/analysis/__init__.py
trackintel/analysis/tracking_quality.py

closes #92
corresponding tests and docs are added.

ENH: tracking quality module

---

tests/io/test_file.py
trackintel/io/file.py

CLN: Added explicit parameters for read_csv functions.

---

tests/preprocessing/test_positionfixes.py

ENH: Use standard geopandas testing function

---

tests/analysis/test_transport_mode_identification.py
tests/geogr/test_distances.py
trackintel/analysis/transport_mode_identification.py
trackintel/geogr/distances.py

Functionality to calculate the length of triplegs (or linestrings) using the haversine distance.
(The pull request before got mixed with another pull request)

ENH: Wgs84 length

---

tests/io/test_from_geopandas.py
trackintel/io/__init__.py
trackintel/io/from_geopandas.py

CLN: Updated function name (#129)

---

tests/preprocessing/test_filter.py

added two tests for increasing test coverage.

TST: added tests for spatial_filter

---

tests/analysis/test_tracking_quality.py
trackintel/analysis/tracking_quality.py

DOC/BUG: correct datamodels for temporal_tracking_quality

---

docs/modules/io.rst
tests/io/test_file.py
tests/io/test_from_geopandas.py
tests/preprocessing/test_triplegs.py
trackintel/io/__init__.py
trackintel/io/dataset_reader.py
trackintel/io/file.py
trackintel/io/from_geopandas.py
trackintel/model/locations.py

Changes in the io module:
- change datetime convert method to `pd.to_datetime`
- change geopandas import function names. closes #129
- rearrange test function structure
- ensure consistent doc style

ENH/DOC: io folder consistency

---

.github/workflows/black.yml

CI of black which checks if the code from the current pull request (and repo) adheres to the black format. 
Would fail if some files need to be changed. **It will not automatically convert code into black style**
Additional parameter `-l 120` sets the line length to 120

ENH: black CI

---

trackintel/io/file.py

DOC: update datatype description

---

tests/preprocessing/test_positionfixes.py
tests/preprocessing/test_triplegs.py
trackintel/preprocessing/positionfixes.py
trackintel/preprocessing/triplegs.py

BUG: extra columns #203

---

docs/modules/analysis.rst
tests/analysis/test_location_identification.py
tests/examples/test_examples.py
trackintel/analysis/location_identification.py

Added simple location identifier freq. That algorithm simply selects the location that the user spend the most time on.
Other "recipes" will be much easier to program as they build all on the same principle.

ENH: Add simple location identifier.

---

ROADMAP.md
docs/conf.py
trackintel/__version__.py

We can discuss the future milestones in this PR

BLD: update for the v1.0 release

---

tests/visualization/test_locations.py
tests/visualization/test_staypoints.py
tests/visualization/test_triplegs.py

BUG: fix action failed bug

---

.gitattributes

fix #208
from: [https://stackoverflow.com/questions/34713765/github-changes-repository-to-wrong-language](https://stackoverflow.com/questions/34713765/github-changes-repository-to-wrong-language)

BUG: Wrong language assigned to repo

---

trackintel/preprocessing/staypoints.py

BUG: fixed geo col names in generate_locations

---

.gitattributes
docs/modules/io.rst
tests/analysis/test_label.py
tests/io/test_dataset_reader.py
tests/preprocessing/test_triplegs.py
trackintel/analysis/label.py
trackintel/io/dataset_reader.py
trackintel/model/triplegs.py
trackintel/preprocessing/positionfixes.py
trackintel/preprocessing/staypoints.py
trackintel/preprocessing/triplegs.py

CLN: A variety of smaller consistensy issues

---

tests/analysis/test_tracking_quality.py
trackintel/analysis/tracking_quality.py

Two enhancements for the `tracking_quality()`/`_split_overlaps()` function:
- previously `_split_overlaps` split records that span several days in midnight, e.g., a record that span 2 days is split into _started_at - 23:59:59_ and _00:00:00 - finished_at_, which means 1 second is lost whenever we perform a split. Now this is changed into _started_at - 00:00:00_ and _00:00:00 - finished_at_. Tests are changed accordingly.
- previously `_split_overlaps` did not deal with `duration` column. Now, this column is updated in the function.

ENH: tracking_quality function

---

ci/envs/37-latest-conda-forge.yaml
ci/envs/38-latest-conda-forge.yaml
ci/envs/39-latest-conda-forge.yaml
docs/environment.yml
environment.yml
requirements.txt

BLD: delete imageio dependency

---

.gitattributes
tests/preprocessing/test_staypoints.py
trackintel/preprocessing/positionfixes.py
trackintel/preprocessing/staypoints.py
trackintel/preprocessing/triplegs.py

ENH: Change for loop to groupby

---

trackintel/analysis/location_identification.py
trackintel/io/file.py
trackintel/io/from_geopandas.py
trackintel/io/postgis.py
trackintel/preprocessing/positionfixes.py

ENH: correct dataframe check

---

docs/_templates/layout.html
docs/conf.py
docs/modules/analysis.rst

ENH: Added links to source codes

---

tests/preprocessing/test_positionfixes.py
trackintel/preprocessing/positionfixes.py

BUG: Fix tripleg generation

---

tests/analysis/test_location_identification.py
trackintel/analysis/location_identification.py

closes #247 
Thanks Henry for the thorough bug report.
Fix that both bool Series use same index.

BUG: Index error in `pre_filter_locations`

---

tests/preprocessing/test_staypoints.py
trackintel/preprocessing/staypoints.py

BUG: fixed 279 + tests

---

trackintel/preprocessing/triplegs.py

BUG: Only numerical data for "user_id".

---

docs/environment.yml

Trying to solve the documentation issue #310

BLD: Update environment.yml

---

tests/analysis/test_tracking_quality.py
trackintel/analysis/tracking_quality.py

BUG: Fix loop

---

trackintel/preprocessing/staypoints.py

Thanks for spotting this error in the documentation!
Let me know if it appears anywhere else; I couldn't find anything at this point.

DOC: fix error in documentation of staypoint merging

---

tests/model/test_util.py
trackintel/model/locations.py
trackintel/model/positionfixes.py
trackintel/model/staypoints.py
trackintel/model/triplegs.py
trackintel/model/trips.py
trackintel/model/util.py

This function isn't meant to be externally visible.
Also add a docstring describing the function a bit.

CLN: Turn `copy_docstring` to a protected function.

---

trackintel/io/file.py

closes #336 
Add missing examples and arguments to the docstrings in io.file
Removed unused imports as well.

DOC: Add missing examples/arguments to io-csv docstrings.

---

tests/model/test_trips.py
tests/preprocessing/test_triplegs.py
tests/preprocessing/test_trips.py
trackintel/io/file.py

closes #343 
Now we can read csv with different geometry names.

ENH: Add `geom_col` for read_csv functions

---

README.md
ci/envs/37-latest-conda-forge.yaml
ci/envs/38-latest-conda-forge.yaml
ci/envs/39-latest-conda-forge.yaml
docs/conf.py
docs/environment.yml
environment.yml
requirements.txt
setup.py

closes #353 
See #353 for more informations.

ENH: Add pygeos to requirements

---

docs/modules/io.rst
tests/io/test_postgis.py
trackintel/io/__init__.py
trackintel/io/postgis.py
trackintel/model/tours.py

Added function `read_tours_postgis` and `write_tours_postgis` to read/write to a PostGIS database. 
Also integrated that to the tours accessor and documentation.

ENH: Enable postgis integration for tours

---

tests/io/test_dataset_reader.py
trackintel/io/dataset_reader.py

CLN: Change labels from defaultdict to dict

---

docs/conf.py
trackintel/__version__.py

Increase version number of new release (closes #363 )
@henrymartin1  or @hong2223 , can you check whether my draft for the release looks okay and whether there is something else that I forgot to do for the release? Thanks :)

BLD: release 1.1.5

---

tests/io/test_postgis.py
trackintel/io/from_geopandas.py
trackintel/io/postgis.py

Bugfix for reading extent correctly from postgis.
Closes #365

BUG: Load extent correctly from postgis

---

trackintel/io/file.py

closes #374 
The bug also appeared on other places, so I changed these as well.

BUG: set `geometry` argument to `geom_col`

---

docs/modules/model.rst
sql/create_tables_pg.sql
trackintel/model/locations.py
trackintel/model/positionfixes.py
trackintel/model/staypoints.py
trackintel/model/tours.py
trackintel/model/trips.py

CLN: Remove unused columns in SQL model

---

tests/geogr/test_distances.py
trackintel/geogr/distances.py

Rewrite logic of `check_gdf_crs` to be more flat and added test for missed testcase.

ENH: Add test for check_gdf_crs

---

tests/preprocessing/test_util.py
trackintel/preprocessing/util.py

Rewrote the `calc_temp_overlap` function to make it simpler and to eliminate states that are not reachable &rarr; increasing the coverage of the code.

ENH: increase coverage for calc_temp_overlap

---

tests/analysis/test_location_identification.py
trackintel/analysis/location_identification.py

BUG: Set index for mask in location_identifier

---

tests/visualization/test_modal_split.py
trackintel/visualization/modal_split.py

BUG: Error axis argument ``plot_modal_split``

---

tests/analysis/test_modal_split.py
trackintel/analysis/modal_split.py

Refactored `calculate_modal_split` function to increase coverage and simplify logic.

ENH: Refactor ``modal_split``

---

tests/preprocessing/test_triplegs.py
trackintel/preprocessing/triplegs.py

The generating functions are generally too long. 
This leads to hard to maintain code, as reading through 300+ lines of code to find an bug is quite time consuming.
As a first change this PR encapsulates the preparation for the `sp_tpls` object into a separate function.
Additionally this PR corrects a bug that causes used columns to be accidentally ([here ](https://github.com/mie-lab/trackintel/blob/c401f3d7e38f1ef60e7db877f4793c7e78f6c3bd/trackintel/preprocessing/triplegs.py#L275) column "type") deleted without warning. This allows us to use this function without assuming which columns might be used by the function.

ENH: Put concat of ``sp_tpls`` for ``generate_trips`` in own function

---

.readthedocs.yml

fixes #425 
Forget about conda. Its mamba time 😎

BLD: Use mamba for docs

---

docs/modules/preprocessing.rst
tests/preprocessing/test_triplegs.py
trackintel/preprocessing/__init__.py
trackintel/preprocessing/triplegs.py

closes #424
Removes `smoothen_triplegs` and all references.

CLN: remove `smoothen_triplegs`

---

.github/envs/39-latest-conda-forge.yaml
environment.yml
requirements.txt

BLD: delete shapely version dependence

---

tests/analysis/test_tracking_quality.py
tests/model/test_locations.py
tests/preprocessing/test_filter.py
tests/preprocessing/test_positionfixes.py
tests/preprocessing/test_staypoints.py
trackintel/io/dataset_reader.py
trackintel/model/util.py
trackintel/preprocessing/staypoints.py
trackintel/preprocessing/triplegs.py

TXT: Fix warnings in tests

---

tests/preprocessing/test_positionfixes.py
trackintel/preprocessing/positionfixes.py

BUG: fix tripleg generation from positionfixes with string user ID

---

environment-dev.yml
requirements-dev.txt

closes #407 
Found a development environment file really useful. So I copied the style from geopandas and added it here.
If there are some packages missing, I'll gladly add them.

ENH: add development environments

---

requirements-dev.txt
requirements.txt

BLD: remove unused dependency virtualenv

---

benchmarks/ASV-BENCHMARKING.md

@hongyeehh Replaced "I" with "we" in the benchmarking doc

DOC: Update ASV-BENCHMARKING.md

---

tests/io/test_postgis.py
trackintel/io/postgis.py

ENH: Store trips list as JSON in postgis

---

tests/analysis/test_location_identification.py
trackintel/analysis/location_identification.py

BUG: Handle empty data in FREQ location_identifier

---

docs/modules/model.rst
tests/model/test_triplegs.py
tests/preprocessing/test_triplegs.py
trackintel/__init__.py
trackintel/io/postgis.py
trackintel/model/__init__.py
trackintel/model/triplegs.py
trackintel/visualization/triplegs.py

Here comes the next class :)
For more info see #490 .

ENH: enable subclassing for Triplegs

---

README.md

This is just in case we wish to showcase our downloads; Currently it stands at around 32K, which, I think, is a decent number.
Please feel free to reject if it is too early :)

DOC: Include `pip` downloads

---

.github/envs/39-latest-conda-forge.yaml

I cannot replicate the build error of #520.
Thus I try to change the `environment.yml` file of the test to see if the error remains.

BLD: replicate local environment.yml for CI

---

trackintel/io/file.py

Replaced `.apply` with vectorized `shapely` version in `write_xyz_csv` functions

ENH: speedup to_csv functions

---

tests/io/test_from_geopandas.py
trackintel/analysis/tracking_quality.py
trackintel/io/from_geopandas.py

Vectorized some Timestamp calculations. I don't think it increases performance by a large margin, I just found it nice.

ENH: vectorize Timestamp calculations

---

README.md

Small readme update.
Added `&rarr;` arrows instead of `->`.
Shortened paths to `io` functions.

DOC: update README

---

docs/modules/analysis.rst
tests/analysis/test_metrics.py
trackintel/analysis/__init__.py
trackintel/analysis/metrics.py
trackintel/model/staypoints.py

I did not know where to put the function, so I put it so far into a new file in `analysis`.
Added branch to calculate planar distances as well.

ENH: add radius of gyration

---

trackintel/analysis/labelling.py
trackintel/analysis/metrics.py
trackintel/analysis/tracking_quality.py
trackintel/io/postgis.py
trackintel/model/trips.py
trackintel/preprocessing/filter.py
trackintel/preprocessing/staypoints.py

I checked my documentation from #563 and saw that the bullet points were not parsed correctly by sphynx.
So I changed that and all the other places where similar errors occurred.

DOC: fix indention

---

trackintel/model/staypoints.py
trackintel/model/triplegs.py

`generate_trips` method pointed to the wrong function.

DOC: fix docstrings

---

tests/io/test_dataset_reader.py
trackintel/io/dataset_reader.py

BUG: raise Error for missing files in read_gpx

---

trackintel/io/dataset_reader.py

DOC: fix link in `read_geolife`

---

tests/analysis/test_metrics.py
trackintel/analysis/metrics.py

BUG: calculate duration in radius_gyration

---

docs/modules/preprocessing.rst
trackintel/preprocessing/__init__.py

DOC: add util functions into docs

---

tests/geogr/test_distances.py
tests/preprocessing/test_positionfixes.py
tests/preprocessing/test_triplegs.py
tests/preprocessing/test_trips.py
tests/preprocessing/test_util.py
tests/visualization/test_plotting.py

TST: Fix pandas warning

---

docs/conf.py
trackintel/__version__.py

BLD: new release info
