mie-lab/trackintel

docs/conf.py, setup.py, tests/preprocessing/test_preprocessing.py, trackintel/preprocessing/staypoints.py
- change the `cluster_staypoints `function: the DBSCAN now directly accepts the distance metric and does not use a pre-calculated pairwise distance matrix.
- add test for haversine distance DBSCAN
- update author information
=> cluster_staypoints: add support for big data

tests/preprocessing/test_preprocessing.py, trackintel/model/staypoints.py, trackintel/preprocessing/staypoints.py
- `epsilon` value is retained for `buffer` function for linestring and point geometry.
- fix geometry generation for dataset locations: same geometry across users
- ensure location_id start from 0
- add `cluster_staypoints` function in `StaypointsAccessor` to ensure consistency
=> fix bugs in cluster_staypoints function

.github/workflows/python-package.yml, tests/io/test_postgis_gpd.py
a hot fix for the failing postgresql/postgis test. In the long run we should see how it is fixed in geopandas but for now this works. I have tested that it can still successfully identify skipped postgis tests as failing in the postgis run.
=> Ci postgis

tests/geogr/test_distances.py, tests/geogr/test_point_distances.py, tests/io/test_file.py, tests/io/test_from_geopandas.py, tests/preprocessing/test_filter.py, tests/preprocessing/test_positionfixes.py, tests/preprocessing/test_staypoints.py, tests/preprocessing/test_triplegs.py, tests/test_staypoints.py, trackintel/io/dataset_reader.py, trackintel/io/file.py, trackintel/io/from_geopandas.py, trackintel/model/positionfixes.py, trackintel/model/staypoints.py, trackintel/model/tours.py, trackintel/model/triplegs.py, trackintel/model/trips.py, trackintel/preprocessing/staypoints.py
Trackintel is now timezone aware
- all required datetime columns are now forced to have a timezone and a fixed datatype using an assert statement in the accessors
- all io functions (except for postgis!) now import timezone aware using an optional timezone argument. If nothing is provided they warn and assume UTC
- Tests are updated according to these changes
- Reformated files according to PEP8 + numpy docstring standards
This solves issue #18
=> Fix datetime type

CONTRIBUTING.md, README.md
Moving contributing related items from `readme.md` file to `contributing.md` file.
Update the commit message conventions (`geopandas` follow `pandas` conventions)
=> DOC: update readme and contributing

tests/analysis/test_tracking_quality.py, trackintel/analysis/tracking_quality.py
closes #162 
ENH: 
- The relative to the dataset start and user start time is a bit confusing, I added a description in the docstring. Line 34-36.
- granularity = weekday and week is added. Now we have all options. The tests are added, but as even geolife_long does not include records for several weeks, the tests for weekday and week might not be useful. I have tested the code using MOBIS and SBB to make sure they produce correct results.
BUG: 
- previously using groupby we did not include timesteps that have no tracking (e.g., a user is tracked in week 4 and 6 but not 5, week 5 will then not be included in the final quality df). This is solved using `_get_all_quality(df, raw_quality, granularity)` to fill in the untracked periods with quality=0. This facilitates subsequent dataset level …
=> ENH/BUG/PERF: tracking quality module

tests/io/test_dataset_reader.py, tests/io/test_file.py, trackintel/io/dataset_reader.py, trackintel/io/file.py
When loading pfs from csv, the bottleneck is in `df['tracked_at'] = df['tracked_at'].apply(dateutil.parser.parse)`. This per-row operation is expensive and can be changed to `df["tracked_at"] = pd.to_datetime(df["tracked_at"])`, which is much faster for common datatime formats and will call `dateutil.parser.parse` if receiving non-common ones. Since we work directly with pd, line 96-99 is no longer needed.
Additional tests for setting tz is added.
The test stricture of test_file.py is incorrect, but I only changed the `TestPositionfixes` class.
=> PERF: datatime loading

tests/examples/test_examples.py
Should fix the Lint Action error. The action we took will always pip install the newest version of black (current 21.4b2), which sometimes is not in line with our local version (my local version was 20.8b1). 
The current solution is to `pip uninstall black` then `pip install black` to force update the black version.
=> CLN: fix black error

README.md
The old badge does not work anymore because we switched away from travis
=> FIX: Update CI badge

tests/io/test_dataset_reader.py, trackintel/io/dataset_reader.py
closes #253
Before using `read_geolife` and `pfs.as_positionfixes.to_csv` will create two duplicate columns `lon` and `longitude`.
=> ENH: fix read_geolife lat lon naming

ci/envs/37-latest-conda-forge.yaml, ci/envs/38-latest-conda-forge.yaml, ci/envs/39-latest-conda-forge.yaml
The github action error originated from a **pandas** [update](https://github.com/pandas-dev/pandas/issues/42356) and triggered a **tqdm** function [calling error](https://github.com/tqdm/tqdm/issues/1199).
This shall be solved in the next **tqdm** release [next release v4.61.2 #1180](https://github.com/tqdm/tqdm/pull/1180), until then we could limit our **pandas** version to **pandas <= 1.2.5**
Also, the **numpy** update to v1.21 introduces new warnings in our test function [DEP: Deprecate error clearing for special method in array-coercion #19001](https://github.com/numpy/numpy/pull/19001), which _I think_ relates to **shapely** methods. We need to wait for **shapely** to suppress the warnings
=> BLD: restrct pandas version - fix test error

examples/trackintel_basic_tutorial.ipynb, tests/io/test_from_geopandas.py, trackintel/io/from_geopandas.py
closes #262
The geometry is now not renamed anymore and instead accessed via the attribute. The attribute was furthermore renamed from `geom` to `geom_col`. This requires a **change in the tutorial notebook**. 
Also, the tests fail because the generated table (e.g. `pfs_from_gpd`) does not correspond to the ground truth table loaded from a csv file (e.g. `tpls_from_csv`). To avoid a change in the test data, I renamed the column of the ground truth table in the test file.
=> Access geometry via geom_col attribute without renaming

tests/preprocessing/test_positionfixes.py, tests/preprocessing/test_staypoints.py, tests/preprocessing/test_triplegs.py, trackintel/preprocessing/positionfixes.py
closes #245
`gap_threshold` now default to 15 minutes. If signal is missing larger than `gap_threshold`, no staypoint will be generated. An example is given below. The signal between 469 and 470 is missing for several hours; originally this will generate a staypoint with a long duration, but setting `gap_threshold=15` will ignore this staypoint.
Some of our old test functions only worked when setting `gap_threshold` large. 
We have a test function `test_temporal` to test the different combinations of `time_threshold` and `gap_threshold`
=> ENH: gap_threshold for generate_stps

.gitignore
Would be nice if we could add these things to the gitignore, for avoiding the OSX DS_Store files.
=> CLN: osx specifics in gitignore

docs/tutorial.rst, examples/import_export_postgis.py, examples/setup_example_database.py, tests/io/test_file.py, tests/io/test_postgis_gpd.py, trackintel/io/postgis.py, trackintel/model/locations.py, trackintel/model/positionfixes.py, trackintel/model/staypoints.py, trackintel/model/triplegs.py, trackintel/model/trips.py
closes #227 
closes #211
The following changes in this pull request.
- Decorator to handle not only connection strings, but also engines/connection objects
- WKT transformation for locations extent
- Updating accessor arguments (adding missing ones and `if_exists` to "fail".
- new argument `sql` instead of fix string.
- handing building GeoDataFrame to `read_*_gpd` functions
=> ENH: Update read_*_postgis functions.

.gitignore, README.md, docs/conf.py, docs/modules/model.rst, tests/preprocessing/test_positionfixes.py, trackintel/__version__.py, trackintel/preprocessing/positionfixes.py
closes #209 
Added the function `copy_docstring` decorator that uses `functools.update_wrapper` to copy the docstring from the method to the accessor.
To copy the docstring from another function, the other function must be defined at creation time, so I added many imports for all functions. It needs to be verified that it works on other machines before we merge it, because I'm not sure if relative or absolute imports are used on my machine (and if that would matter).
=> ENH: Copy docstring for accessor methods.

tests/preprocessing/test_triplegs.py, trackintel/model/triplegs.py, trackintel/preprocessing/triplegs.py
fixes #219
Main idea of the new implementation is that we assign a trip_ids to a combined dataframe of triplegs and staypoints so that we are able to create trips using a groupby statement that is based on the assigned trip id.
The implementation itself has several main steps:
0. Merge triplegs and staypoints into a single dataframe and sort them by [user_id, started_at]
1. identify start of new trips (activities, user change, temporal gaps) 
2. assign trip ids to all triplegs/staypoints that belong to a trip
3. delete activities as they are not part of trips
4. group by trip_id to create trips
5. add activities again to trip dataframe to assign origin_staypoint_id and destination_staypoint_id
6. delete activities again
7. Do some id stuff
Some tests are already passing but I have added …
=> ENH: Cleaner and faster trip generation

tests/preprocessing/test_positionfixes.py, tests/preprocessing/test_staypoints.py, tests/preprocessing/test_triplegs.py, trackintel/preprocessing/positionfixes.py, trackintel/preprocessing/staypoints.py, trackintel/preprocessing/util.py
closes #289
The general function `applyParallel()` is defined in `trackintel.preprocessing.util`. The `print_progress` argument is passed to the function for progress monitoring. 
A simple performance comparison of `generate_staypoints()` function on the whole Geolife dataset: before 2100s, current 1000s (using 20 workers; seems that the main part takes 200s and the other 800s is occupied by the post-processing.)
No tests are currently available. I manually compared (`pd.assert_frame_equal()`) the result of before and after the place of change. But integrating this would be a very long test (basically keep the old generate function and compare it against the new one), and I am not sure if this is worth it. On the other hand, passing all of our previous tests is already a type of testing? …
=> ENH: Parallel version for generate functions

tests/io/test_file.py, tests/io/test_from_geopandas.py, trackintel/io/from_geopandas.py, trackintel/preprocessing/triplegs.py
closes #278 
Default of `read_*_gpd` functions now opt for the geometry of the GeoDataFrame if available.
Also added a function `_trackintel_model` that the functions call instead of doing everything themselves.
Added tests for this new function.
Added crs keyword to all `read_*_gpd` functions.
Added "extent" to `read_locations_gpd`.
Added geometry to `read_trips_gpd`
Set default from `mapper` from `{}` to `None` to avoid bugs with mutable datatypes.
~~Two test are still missing~~
~~1. checking if `read_trips_gpd` correctly return either DataFrame or GeoDataFrame.~~
~~2. checking if `read_locations_gpd` can handle an "extent" column.~~
I just wanted to to have a small and clean PR and now we have already 400 changed lines. :]
=> ENH: Default to geometry for `read_*_gpd` functions.

tests/io/test_postgis.py, trackintel/io/postgis.py
closes #277 
closes #301 
Added all `from_postgis` kwargs to `read_*_postgis` functions so that the arguments of `read_*_gpd` functions are also accessible via keywords arguments.
Also added distinction between the two trip models.
=> ENH: `read_*_gpd` arguments available for `read_*_postgis` functions.

trackintel/preprocessing/triplegs.py
Closes #305 
I solved the problem differently than we discussed. 
The GeoDataFrame is only created in this `if add_geometry` block, so I moved the block after using the exploding, that way we only use the DataFrame variant.
Creating a test for this is a bit difficult because we need to specify the geopandas version. So I just leave it without one.
=> BUG: Explode function now only called on dataframes.

setup.py, trackintel/__init__.py, trackintel/core.py
Issue:
`ti.__version__` was not printing anything; It was returning a pointer to a function whereas `__version__.__version__` and `__version__.VERSION` were printing the version name.
Test: 
Previously we had: 
After this fix, we have:
Soluton based on [this]( https://stackoverflow.com/a/16084844/3896008 ) stackoverflow answer from users: [sorin](https://stackoverflow.com/users/99834/sorin) and [nico-schlömer](https://stackoverflow.com/users/353337/nico-schl%c3%b6mer)
=> ENH: embed version number 

docs/modules/preprocessing.rst, tests/preprocessing/test_staypoints.py, trackintel/preprocessing/staypoints.py
closes #342 
The documentation is updated to include that the location id must be part of the staypoints dataframe. I also added an assert statement and a corresponding test. 
Also the issue of changing datatypes in the staypoints table should be fixed, but maybe you can test this with your data
=> CLN: update documentation and fix datatype issues in staypoint merging

trackintel/geogr/distances.py
closes #335 
Added example to `geogr.calculate_distance_matrix()`
Added example to `geogr.meters_to_decimal_degrees()`
=> DOC: Add missing examples `geogr` functions.

trackintel/visualization/osm.py, trackintel/visualization/util.py
Added examples for:
- `a4_figsize`
- `save_fig`
- `plot_osm_streets`
`regular_figure` I deemed too trivial to include an example.
closes #340
=> CLN: Add examples for visualization functions

trackintel/preprocessing/trips.py, trackintel/preprocessing/util.py
closes #339 
Added examples for:
- `generate_tours`
- `get_trips_grouped`
- `calc_temp_overlap`
- `applyParallel`
=> CLN: Add examples to `preprocessing` functions

tests/io/test_dataset_reader.py, trackintel/io/dataset_reader.py
Splits `read_geolife` into two parts. 
I stumbled across the implementation of reading geolife data in [scikit-mobility](https://github.com/scikit-mobility/scikit-mobility/blob/7c50c09adda71338c19dcc03f0e11beb747ca71e/skmob/io/file.py#L82) , which in fact is very clean.
That I wanted also for our implementation. That worked out, at least for me the function seems simpler (but I am probably biased).
What is changed:
1. Dict of labels get generated in `_get_labels` for modularity.
2. `_get_df` now a generator to efficiently concat all these trajectories
without building a huge list containing all data. &rarr; limiting the
memory footprint.
=> ENH: Redo `read_geolife` for smaller memory footprint

README.md, tests/analysis/test_tracking_quality.py, trackintel/analysis/tracking_quality.py
closes #258
main changes:
- We use pd.Grouper to group days or weeks and return the datatime object. The granularity == "day" and "week" now only returns the absolute date. 
- As we have no relative days, we no longer fill in quality == 0 records (_get_all_quality() is now unused).
- Description added to the docstrings
=> ENH: use pd.Grouper for tracking quality

tests/geogr/test_distances.py
Fixes the error originated from `sklearn.metrics.pairwise_distances`: The atol is increased to 0.01 (1cm) instead of 0.001 (1mm). 
I suspect the error originated from their new 1.0.2 release, but I did not find any related changes in their [changelog](https://scikit-learn.org/dev/whats_new/v1.0.html#sklearn-metrics)
=> TST: Fix test error

tests/preprocessing/test_util.py, trackintel/preprocessing/positionfixes.py, trackintel/preprocessing/triplegs.py, trackintel/preprocessing/util.py
closes #326 
Adds new function `_explode_agg` and tests for that function.
This function is used in `generate_trips` and `generate_staypoints`.
=> ENH: Add `_explode_agg` to simplify id assignment in staypoint generation

.github/envs/39-latest-conda-forge.yaml, .github/workflows/CI-tests.yml, README.md, docs/conf.py, docs/environment.yml, environment.yml, requirements.txt, setup.py, tests/analysis/test_location_identification.py, tests/preprocessing/test_triplegs.py, trackintel/geogr/point_distances.py, trackintel/preprocessing/positionfixes.py
I tinkered around a bit and looked at the code of the staypoint generation as that takes always a lot of time. 
Found out that most of the time is spent accessing the x and y coordinates (shapely is slow) so I have thrown the coordinates into numpy arrays. That way the access takes nanoseconds instead of microseconds.
I also moved some calculation outside of the for-loop to speedup the time comparisons but those improvements are rather minor.
Now the limiting factor is the distance function. For this reason I replaced the casting to radians with `np.deg2rad` as this is some microseconds faster.
This results in a speed up of around a factor 5. (Tested on my laptop with users 51 and 52)
- Before the changes it took around 52 seconds
- After the changes it takes around 11 seconds
If we want …
=> ENH: 5x speed increase for staypoint generation

tests/preprocessing/test_triplegs.py, tests/preprocessing/test_util.py, trackintel/preprocessing/util.py
Dtype of index changed after using the `_explode_agg` function because nan are filtered one step too late.
=> BUG: Fix dtype change in `_explode_agg`

tests/analysis/test_location_identification.py, tests/analysis/test_tracking_quality.py, tests/io/test_dataset_reader.py, tests/preprocessing/test_positionfixes.py, tests/preprocessing/test_staypoints.py, tests/preprocessing/test_triplegs.py, trackintel/analysis/tracking_quality.py
In future versions of Pandas, `concat` will be deprecated. 
Read more about this [here](https://github.com/pandas-dev/pandas/issues/35407).
=> ENH: Replace df.append with pd.concat (Future warning)

tests/analysis/test_tracking_quality.py, trackintel/analysis/tracking_quality.py
This PR does quite a lot because some changes where necessary to generalize this method.
- use `dt.ceil()` and `dt.floor()` to handle the splits more generally.
- fixed multiple bugs that come from using `.date`/`.hour` (if on same date on different months it wouldn't be recongized)
- wrote test for corner cases in `_split_overlap`
- wrote test for helpfunction `_get_split_index`.
- some cleanup and speedup here and there
closes #369
=> ENH: `_split_overlap` splits now exactly on border

.github/envs/39-latest-conda-forge.yaml, docs/environment.yml, environment.yml, requirements.txt, setup.py, trackintel/io/file.py, trackintel/io/from_geopandas.py
I have read about some black magic in the `inspect` module and wanted to change how we do the warning when `index_col` is not explicitly set. Previously we used `index_col=object()` as the default value, now with the `_index_warning_default_none` wrapper we can use `index_col=None` as we can see what keyword arguments the user has provided.
As a bad habit of mine, I also saw that the io functions redo a lot of code that we have already implemented in the `from_geopandas` module. So I went ahead and minimized the work we do in the file IO functions. 
- Added `_index_warning_default_none` to handle non-explicit set `index_col`
- ``read_*_csv`` function now call their ``read_*_gpd`` counterparts
=> ENH: Refactor file IO

tests/preprocessing/test_triplegs.py, tests/preprocessing/test_trips.py, trackintel/preprocessing/trips.py
Shapely 2.0.0 will do some internal refactoring to improve performance (based on pygeos), but will also bring some changes. Read more about it [here](https://shapely.readthedocs.io/en/latest/migration.html).
So far, these changes have only generated warnings, but I've updated the relevant sections.
This doesn't involve much more than adding `.geoms` everywhere so that it works as before.
=> ENH: Handle shapely 2.0 deprecation warnings

tests/analysis/test_tracking_quality.py, trackintel/analysis/tracking_quality.py
When I updated `split_overlaps` in #384, I had an idea for an alternative implementation.
I am not completely happy with mine either because I had to use the `apply` method. I did not find another way with the two datetime columns ["started_at", "finished_at"]. The logic is simpler, but I haven`t looked at the performance.
So this is more a suggestion, if you think this is a bad idea, we can drop it.
This PR contains:
- removed unused method `_get_all_quality`
- removed `max_iter` keyword argument.
- created new function `_get_times` that returns list of start-end times.
- applied this function to all rows for a more elegant split.
- wrote test for new `_get_times` function.
=> ENH: Simplified logic in `_split_overlaps`

.github/envs/39-latest-conda-forge.yaml, README.md, docs/conf.py, docs/environment.yml, environment.yml, requirements.txt, setup.py, tests/geogr/test_distances.py, trackintel/geogr/distances.py
Increased the speed of this method by using methods from pygeos.
Removed `_calculate_haversine_length_single` and updated the test as before nothing was really tested.
closes #401
Edit: Added pygeos to environment that should lead to no further dependencies as geopandas already uses it.
=> ENH: speedup of calculating haversine LineStrings length

tests/preprocessing/test_triplegs.py, trackintel/preprocessing/triplegs.py
The `smoothen_triplegs` has the bug that it tries accessing the geometry over the "geom" column. 
This PR fixes this. But generally I would also suggest removing this function as the wrapper is so thin that I don't see the advantage in adding it to trackintel.
=> BUG: access geometry in smoothing correctly

tests/preprocessing/test_positionfixes.py
Related to #382 
Handled pytest's warning that no argument was given for `pytest.warns`.
Also fixed a small bug that a string was intended for regex matching when regex was not used.
=> TST: Set arg UserWarning instead of None

.github/envs/39-latest-conda-forge.yaml, docs/environment.yml, environment.yml, requirements.txt, setup.py
Related to #415 
Sets version number of pygeos to `>=0.10.0` to be able to use the `return_index` keyword [here](https://github.com/mie-lab/trackintel/blob/c401f3d7e38f1ef60e7db877f4793c7e78f6c3bd/trackintel/geogr/distances.py#L256).
=> BLD: set lowest pygeos version number

tests/model/test_util.py, trackintel/model/util.py
Minor performance increase. Replaced a `apply` call with the direct vectorization.
Additionally replaced the asserts with raised errors as asserts should be used to detect bugs and not to communicate missing parameters. (e.g. https://stackoverflow.com/questions/944592/best-practice-for-using-assert?noredirect=1&lq=1)
=> ENH: Remove `.apply` in `get_speed_triplegs`

tests/preprocessing/test_positionfixes.py, trackintel/geogr/point_distances.py, trackintel/preprocessing/positionfixes.py
This PR increases the performance of `staypoint_generation` by 4x. We achieved that by adding an extra mode to `haversine_distance` that uses `math` functions functions that avoid the overhead of `numpy` functions and is that way 10x faster.
That is of course only possible for float values and not for arrays therefore an extra flag is added that can be set to get this speedup. 
Additionally made some minor cleanups in the function.
=> PERF: faster mode for only floats in haversine distance

trackintel/preprocessing/staypoints.py
I want finally to get rid of these shapely warnings in `preprocessing/staypoints`. 
But for that I want to clean up the method first. I saw that we could easily reuse one function.
So this PR reuses the ``_generate_locations_per_user`` function and refactors there a bit.
=> ENH: generalize `_generate_locations_per_user`

tests/model/test_positionfixes.py, tests/model/test_staypoints.py, tests/model/test_triplegs.py, trackintel/preprocessing/staypoints.py
Geopandas 0.11 is more consistent in the way the conversion from GeoDataFrames to DataFrames are handled, now consistently every time you drop the Geometry column you get a DataFrame back.
This caused one bug in the code and one test bug in some tests.
1. the bug was in `preprocessing/staypoints.py` where the variable `locs` was a GeoDataFrame before the change and is now a DataFrame.
2. accessor tests failed because they expected error messages from a GeoDataFrame for missing geometry columns and not from a DataFrame. 
Release notes here: https://github.com/geopandas/geopandas/releases/tag/v0.11.0
closes #438
=> TST: Failing tests because of geopandas 0.11

trackintel/preprocessing/trips.py
closes #434 
The typo sufficiently annoyed me, so I fixed it quickly :D
=> BUG: fix typo in progress bar printing

README.md
We are using [airspeedvelocity](https://github.com/airspeed-velocity/asv/) for benchmarking trackintel. This pull request puts a badge and a link to the stats
=> ENH: Added asv benchmark badge

tests/preprocessing/test_staypoints.py, tests/preprocessing/test_triplegs.py, trackintel/preprocessing/triplegs.py
closes #442 
As described in #442 , the crs was not set for trips or locations generation in previous versions of trackintel. 
In the meantime, the problem was already solved for location generation (I could not reproduce the error with the new version of trackintel, only with an older version). I therefore just added a test. Also, since the crs can only be set on a dataframe-level, I don't think it's a problem that there are two geometries - the locs crs just needs to be the same as the sp crs in the end.
Regarding the trips generation it is more complicated because they use both sp and triplegs. I therefore added 
1) an error if both crs are set but they contradict (I think we shouldn't concat the geometries into one in that case)
2) a warning if one or both of them are None
3) …
=> BUG: fixed setting crs for tripleg generation

tests/preprocessing/test_trips.py, trackintel/model/util.py
Fixes #449
Apparently the behavior of `pd.merge`  changed after an update.
Other places in the code should not be affected by the `pd.merge` change.
Also fix error in test where override of geometry column resulted in cast to Series with object type.
=> BUG: fix index error pfs_mean_speed

examples/trackintel_basic_tutorial.ipynb, tests/preprocessing/test_triplegs.py, tests/preprocessing/test_util.py, trackintel/preprocessing/util.py
Pandas released v2.0 which causes some errors in our test functions:
- `append` function deprecated and shall be replaced by `concat`:
> Removed deprecated Series.append(), DataFrame.append(), use [concat()](https://pandas.pydata.org/docs/reference/api/pandas.concat.html#pandas.concat) instead ([GH35407](https://github.com/pandas-dev/pandas/issues/35407))
- More flexible dtypes for pandas.index, [link](https://pandas.pydata.org/docs/whatsnew/v2.0.0.html#index-can-now-hold-numpy-numeric-dtypes)
In addition, `infer_datetime_format` argument is depricated:
> Deprecated argument infer_datetime_format in [to_datetime()](https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html#pandas.to_datetime) and [read_csv()](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#panda …
=> TST: test error fixes with pandas 2.0

trackintel/preprocessing/positionfixes.py
Add print progress option to generate_triplegs #414
The progress bar is only valid in CASE 2: pfs do not have a column 'staypoint_id' but staypoint are provided.
Please let me know if my update meets the requirement of this issue.
=> add progress_bar to function generate_tripleg

.github/envs/39-latest-conda-forge.yaml, README.md, docs/conf.py, docs/environment.yml, environment.yml, requirements.txt, setup.py, trackintel/geogr/distances.py, trackintel/preprocessing/util.py
With pygeos being integrated into shapely we don't need this dependency anymore.
Thus this PR removes all calls to pygeos.
=> ENH: replace pygeos with calls to shapely 2.0

trackintel/analysis/location_identification.py
closes #476
This PR removes the `as_staypoints` assertions, as the staypoints need to be created initially and there this property is cached.
It doesn't really solve the verify problem, but my argument is that we require a `GeoDataFrame (as trackintel staypoints)` and thus can rely that we get the right data shape.
In all other places `as_xyz` works as intended, since it is always applied to newly created objects and thus is not yet cached.
However, I would like to make this a bit clearer with a proper class hierarchy (which is backwards compatible with our current `as_xyz` approach), but we should discuss that elsewhere.
=> ENH: remove as_staypoints calls from location_identification

.github/envs/39-latest-conda-forge.yaml, docs/environment.yml, environment.yml, requirements.txt, setup.py, trackintel/model/util.py, trackintel/preprocessing/staypoints.py, trackintel/preprocessing/triplegs.py
As of geopandas 0.12.0, these warnings have been fixed and should no longer be suppressed.
Further should close #463 as the discussed problem does not occur anymore, can be tested with this code:
````python
import geopandas as gpd
import pandas as pd
from shapely.geometry import Point
gdf = gpd.GeoDataFrame([{"a":1, "g": Point(1, 2)}], geometry="g", crs=4326)
gdf_empty = gpd.GeoDataFrame()
gdf_concat = pd.concat([gdf, gdf_empty])
assert gdf.crs == gdf_concat.crs
````
=> ENH: remove warning suppression

CONTRIBUTING.md
Update the instructions on Performance benchmarking and the usage of the `gh-pages` branch.
=> DOC: change contributing file for performance benchmarking

environment-dev.yml, requirements-dev.txt
Due to overlapping PR, the version of geopandas wasn't increased for the dev requirements.
=> BLD: increase geopandas version

tests/io/test_postgis.py, trackintel/io/postgis.py
closes #409 
Split up kwargs into own variable.
Test already existed for this.
=> ENH: separate read_gpd kwargs into own variable

tests/io/test_file.py, trackintel/io/file.py
fixes #485
Used `ast.literal_eval` as `eval` is a bit dangerous.
But I think we need to communicate that this is done for some reason, or that `trips` is a optional column.
This relates to #491.
=> BUG: Read csv lists correctly

tests/io/test_file.py
closes #391 
Default tests already check for `extent`, so I added a little extra test to check if it also works without it.
=> TST: add test for no extent column in locations_csv

tests/analysis/test_location_identification.py, tests/analysis/test_modal_split.py, tests/io/test_postgis.py, tests/model/test_positionfixes.py, tests/model/test_staypoints.py, tests/model/test_triplegs.py, tests/model/test_trips.py, tests/preprocessing/test_staypoints.py
In #498 I copied `assert locs.as_locations` from another test. But we decided in #215 to use `locs.as_locations` to check validity.
To never copy the old style again, this PR removes all of it from the tests (and in addition I removed some `assert True`).
As a sidenote, I think some validity checks don`t work, as discussed in #476, but most are fine.
=> TST: remove unnecessary assert statements from tests

tests/io/test_util.py, trackintel/io/file.py, trackintel/io/postgis.py, trackintel/io/util.py
closes #330 
I moved the decorator for the `read_csv` function to `io/util.py` to make it accessible, and then used it for the postgis functions as well.
Alternatively, we could move it to `io/from_geopandas.py` to avoid creating a new file.
=> ENH: warn in `read_postgis_` functions if no index column is provided

docs/modules/model.rst, tests/model/test_staypoints.py, trackintel/__init__.py, trackintel/analysis/tracking_quality.py, trackintel/io/postgis.py, trackintel/model/__init__.py, trackintel/model/staypoints.py
Here comes the next class :)
For more info see #490 .
=> ENH: enable subclassing for Staypoints

tests/preprocessing/test_positionfixes.py, trackintel/preprocessing/positionfixes.py
closes #514 
Changed `mean` function to `first`. Bug wasn't detected as pandas `mean` interprets strings like `"0"` as numbers for `mean` if necessary.
=> BUG: enable non-numeric dtypes in generate_triplegs

tests/io/test_file.py, trackintel/io/from_geopandas.py, trackintel/model/positionfixes.py, trackintel/model/staypoints.py, trackintel/model/tours.py, trackintel/model/triplegs.py, trackintel/model/trips.py
Replaces all calls of `is_datetime64tz_type(obj)` with `isinstance(obj.dtype, pd.DatetimeTZDtype)`, because it is deprecated in pandas `2.1.0`.
Personally I don't understand why they changed that, but apparently it creates some minor performance increase.
=> ENH: remove `is_datetime64tz_type`

trackintel/analysis/location_identification.py, trackintel/preprocessing/positionfixes.py, trackintel/preprocessing/triplegs.py
Replace `fillna(method="ffill")` with `.ffill()` and replace built-in functions in `.agg` with strings.
=> CLN: fix deprecation warnings for `fillna` and `.agg`

tests/analysis/test_location_identification.py, trackintel/analysis/location_identification.py
For `idxmax` two things got deprecated.
1. the `axis` keyword, this was an easy fix
2. support of columns with only NaT, we relied on this behavior. Thus I needed to rewrite code to handle this.
Further deprecated is `df.loc[idx, "col"] = "string"`; it creates a new column that defaults to `float64`, that type then gets upcasted to `object` when `"string"` gets filled into the dataframe. To avoid this we have to create the column beforehand with `df["col"] = None`.
=> CLN: fix deprecation warnings for `.idxmax` and `.loc[]`

docs/modules/model.rst, tests/model/test_tours.py, trackintel/__init__.py, trackintel/io/file.py, trackintel/io/postgis.py, trackintel/model/__init__.py, trackintel/model/tours.py
The last class. For reference see #490.
=> ENH: enable subclassing for tours

tests/io/test_postgis.py, tests/model/test_util.py, tests/preprocessing/test_triplegs.py
Small PR that removes `print` statements that weren't removed after debugging.
=> TST: remove debug print statements

tests/model/test_util.py, trackintel/model/trips.py, trackintel/model/util.py
Instead of having two GeoDataFrame subclasses I combined them together into one with some conditionals that check if the `fallback_class` is set. This will hopefully make the code a bit better to read.
=> ENH: combine `TrackintelGeoDataFrame` and `TrackintelGeoDataFrameWithFallback` into one class

trackintel/__init__.py, trackintel/io/__init__.py, trackintel/model/__init__.py
I wanted to work on #535 but there is an issue with circular imports. This PR is a cleanup step before that, updating `__init__` files with adding new functions, changing orders such that the trackintel classes are the first things that are imported, and deleting imports that I think are not necessary.
=> ENH: clean up __init__ files

trackintel/geogr/distances.py, trackintel/io/file.py, trackintel/io/postgis.py, trackintel/model/positionfixes.py, trackintel/model/util.py, trackintel/preprocessing/positionfixes.py
This PR removes all imports that were necessary to copy docstrings to the Positionfixes class. 
The docstrings are still copied, but now in the other direction. 
On some level, I dislike this change, as it removes documentation from the code that relies on it, thus making the source code harder to read. On the other hand `@doc` enables to omit the first argument for all the class methods.
If you find the loss of readability worse than the `@doc` tricks, I would also be happy to simply duplicate the docstrings and add comments as a reminder that dependent docstrings should be updated accordingly
=> ENH: remove all potential circular imports from Postfixes

tests/analysis/test_modal_split.py, tests/model/test_locations.py, tests/model/test_positionfixes.py, tests/model/test_staypoints.py, tests/model/test_tours.py, tests/model/test_triplegs.py, tests/model/test_trips.py, tests/model/test_util.py, tests/preprocessing/test_triplegs.py, tests/preprocessing/test_trips.py, trackintel/geogr/distances.py, trackintel/model/locations.py, trackintel/model/positionfixes.py, trackintel/model/staypoints.py, trackintel/model/tours.py, trackintel/model/triplegs.py, trackintel/model/trips.py, trackintel/model/util.py, trackintel/preprocessing/positionfixes.py, trackintel/preprocessing/staypoints.py, trackintel/preprocessing/triplegs.py, trackintel/preprocessing/trips.py
Closes #534  
See there for motivation.
To allow constructions of trackintel class instances that do not follow the model, the additional keyword `validate` has been introduced for all class constructors.
To avoid the wrong data shape, `validate` is now public, when called it throws an exception if the data is not in the correct shape.
=> ENH: remove _check to do validation explicitly

CONTRIBUTING.md, README.md, docs/modules/model.rst, docs/tutorial.rst, examples/import_export_postgis.py, examples/preprocess_trajectories.py, examples/setup_example_database.py, examples/trackintel_basic_tutorial.ipynb, trackintel/analysis/labelling.py, trackintel/analysis/location_identification.py, trackintel/analysis/modal_split.py, trackintel/analysis/tracking_quality.py, trackintel/geogr/distances.py, trackintel/io/dataset_reader.py, trackintel/io/file.py, trackintel/io/from_geopandas.py, trackintel/io/postgis.py, trackintel/model/locations.py, trackintel/model/positionfixes.py, trackintel/model/staypoints.py, trackintel/model/tours.py, trackintel/model/triplegs.py, trackintel/model/trips.py, trackintel/model/util.py, trackintel/preprocessing/filter.py, trackintel/preprocessing/positionfixes.py, trackintel/preprocessing/staypoints.py, trackintel/preprocessing/triplegs.py, trackintel/preprocessing/trips.py, trackintel/visualization/plotting.py
Closes #532 
I replaced in all public visible code sections `as_xyz` with their respective method calls.
Also updated the tutorial minimally to reflect the new class change.
Further the documentation strings `(Geo)DataFrame (as xyz)` got replaced with their respective Trackintel class.
After this #529 should be next.
=> ENH: replace all `as_xyz` with method calls

tests/preprocessing/test_triplegs.py, trackintel/model/staypoints.py
=> ENH: Enable generate_trips for staypoints

benchmarks/preprocessing_benchmarks.py, docs/modules/analysis.rst, docs/modules/geogr.rst, docs/modules/io.rst, docs/modules/model.rst, docs/modules/preprocessing.rst, docs/modules/visualization.rst, examples/trackintel_basic_tutorial.ipynb, trackintel/analysis/location_identification.py, trackintel/analysis/modal_split.py, trackintel/geogr/__init__.py, trackintel/io/dataset_reader.py, trackintel/io/file.py, trackintel/model/locations.py, trackintel/model/positionfixes.py, trackintel/model/staypoints.py, trackintel/model/tours.py, trackintel/model/triplegs.py, trackintel/model/trips.py, trackintel/model/util.py, trackintel/preprocessing/__init__.py, trackintel/preprocessing/staypoints.py, trackintel/preprocessing/triplegs.py, trackintel/visualization/plotting.py
closes #546
Changed how we export and import functions.
This makes the module paths clearer and additionally all links in the documentation work now as well.
=> ENH: Reexport functions from modules

docs/modules/model.rst, trackintel/model/locations.py, trackintel/model/positionfixes.py, trackintel/model/staypoints.py, trackintel/model/tours.py, trackintel/model/triplegs.py, trackintel/model/trips.py, trackintel/preprocessing/triplegs.py
closes #565 
With the new class style mentioning the pandas accessor thing will lead to confusion. 
So I removed it from all documentation. I've done it rather quickly, so if somebody would take a second look at my formulation, I would be really happy about that. :)
=> DOC: replace accessor docs with new class style

trackintel/model/staypoints.py
Fixes small typo from last PR.
=> DOC: fix docstring for `Staypoints.jump_length`

docs/modules/io.rst, tests/data/gpx_data/track1.gpx, tests/data/gpx_data/track2.gpx, tests/io/test_dataset_reader.py, trackintel/io/__init__.py, trackintel/io/dataset_reader.py
That was a lot simpler than I thought.
Currently we assign to all positionfixes `user_id = 0`.
=> ENH: Add gpx reader for single user

tests/preprocessing/test_trips.py, trackintel/preprocessing/trips.py
=> ENH: multiprocessing for generate_tours

docs/modules/geogr.rst, docs/modules/preprocessing.rst, tests/geogr/test_filter.py, trackintel/geogr/__init__.py, trackintel/geogr/filter.py, trackintel/model/locations.py, trackintel/model/staypoints.py, trackintel/model/triplegs.py, trackintel/preprocessing/__init__.py
=> CLN: move spatial_filter to geogr module

tests/geogr/test_distances.py, trackintel/geogr/distances.py
fixes  #592
One of the added tests has a very generous relative tolerance, this is due to #593.
I made this function probably quite a bit slower. I thought that correctness is more important and if nobody experienced this bug in 3 years maybe it isn't called that often either.
Tried to use pairwise distance for everything. That wasn't possible for the LineStrings as sklearn and scipy both enforce float as data type. Thus I copied the code out of sklearn and adapted it a bit.
=> BUG: `calculate_distance_matrix` computes all pairs

tests/geogr/test_distances.py, trackintel/geogr/distances.py
fixes #593 
It wasn't a bug. I just entered `longitude`, `latitude ` into the function instead of `latitude`, `longitude`. 
This PR fixes the test.
=> TST: correct calculate_dist_matrix test

tests/analysis/test_label.py, trackintel/analysis/labelling.py
Just a small PR I came around to do. 
- replaced an `.apply` that assigns categories based on speed with the `pd.cut` function. This complicates the code a bit, but not that much. Moves basically all computation to pandas
- removed an error if the input dictionary isn't sorted and instead just sort the input.
=> ENH: remove .apply in predict_transport_mode

LICENSE, apt.txt, docs/conf.py, tests/visualization/test_plotting.py, trackintel/analysis/tracking_quality.py, trackintel/io/from_geopandas.py, trackintel/preprocessing/trips.py
Just a small cleanup PR. 
- updated the license year
- removed unused `apt.txt` file
- removed unused imports
=> CLN: update license, remove unused imports

tests/analysis/test_label.py, tests/analysis/test_modal_split.py, tests/analysis/test_tracking_quality.py, tests/geogr/test_distances.py, tests/geogr/test_filter.py, tests/model/test_locations.py, tests/model/test_positionfixes.py, tests/model/test_staypoints.py, tests/model/test_triplegs.py, tests/preprocessing/test_positionfixes.py, tests/preprocessing/test_staypoints.py, trackintel/analysis/labelling.py, trackintel/analysis/modal_split.py, trackintel/analysis/tracking_quality.py, trackintel/geogr/distances.py, trackintel/geogr/filter.py, trackintel/model/locations.py, trackintel/model/positionfixes.py, trackintel/model/staypoints.py, trackintel/model/triplegs.py, trackintel/preprocessing/positionfixes.py, trackintel/preprocessing/staypoints.py
A bit of a pet peeve of mine.
All over trackintel we used `AttributeError` where `ValueError` would make more sense.
I changed it where it made sense for me.
for reference: https://docs.python.org/3/library/exceptions.html
>**AttributeError**
Raised when an attribute reference (see [Attribute references](https://docs.python.org/3/reference/expressions.html#attribute-references)) or assignment fails. (When an object does not support attribute references or attribute assignments at all, [TypeError](https://docs.python.org/3/library/exceptions.html#TypeError) is raised.)
e.g.
```python
>> a = object()
>> a.not_existing_field
AttributeError: 'object' object has no attribute 'not_existing_field'
```
> **ValueError**
Raised when an operation or function receives an argument that has the right …
=> ENH: Change AttributeError to ValueError

tests/preprocessing/test_staypoints.py, trackintel/preprocessing/staypoints.py
partly solves #600 by adding a buffer to the extent of all generated locations
=> ENH: add buffer to all generated locs

trackintel/model/util.py
Recently the GeoPandas team had some issues with the `_constructor_from_mgr` and in a change they added [here](https://github.com/geopandas/geopandas/blob/74263151bccd2e26a024719137c4e877cab495ce/geopandas/geodataframe.py#L1634) `_geodataframe_constructor_with_fallback` and this breaks our code. For our code to work they should have to use `self._constructor`, so we do that manually in our code to repair this. 
closes #605
=> BUG: catch `_constructor_from_mgr` from geopandas

examples/preprocess_trajectories.py, tests/preprocessing/test_positionfixes.py, trackintel/model/positionfixes.py, trackintel/preprocessing/positionfixes.py
Following #607, this PR does the following:
- Clean up tests for positionfix generation
- Adding docstring to explain triplegs' time and geometry generation
- Adding more tests, in particular `test_stability()`, to ensure consistency between two cases
=> DOC/TST: generate tripleg

trackintel/visualization/plotting.py
Fixes small deprecation warning for `osmx` that they deprecate passing `north, south, east, west` in favor for `bbox`
=> Fix deprecation warning osmnx

tests/geogr/test_distances.py, trackintel/geogr/distances.py
Fix deprecation warning by making cast to numpy array explicit.
Here pandas complained that `ravel()` is deprecated for Series.
And the only thing it does it inexplicity converting a Series to an array.
=> Fix `ravel` deprecation warning for `Series`

tests/analysis/test_tracking_quality.py, trackintel/analysis/tracking_quality.py, trackintel/preprocessing/triplegs.py
For pandas `3.0.0` they deprecate out many places where they do under the hood copying for `ìnplace` operations. One of these places is the modifying of views on dataframes. Further changed `H` to `h` in `_split_overlaps`
=> fix deprecation warning for `inplace`

tests/preprocessing/test_positionfixes.py
Just a small fix for `test_duplicate_pfs_warning`.
Was confused about some `empty_pfs` warning which turns out can just be captured and ignored as it is expected that it is empty.
=> TST: capture expected warning

tests/io/test_dataset_reader.py, tests/io/test_from_geopandas.py
Fixes the test failures.
Geopandas reached `1.0.0` 🎉 (hopefully things stabilize now...)
With that Geopandas defaults to `pyogrio` instead of `fiona`. Apparently `pygrio` reads integers as i32 if they are small enough and that differentiates to the `pd.read_csv` which always reads them as i64.
As this behavior is understandable, I choosed to ignore the errors.
=> TST: ignore `pygrio` default int32 type

README.md
The temporal_tracking_quality function was relocated to ti.analysis in a recent update of Trackintel. This commit updates the example in the 'How it Works' section of the README to reflect the correct function path, ensuring the example runs without errors.
=> [DOC] Fix incorrect import path of temporal_tracking_quality function in README example

trackintel/model/util.py, trackintel/preprocessing/staypoints.py
closes #644
The issue is raised due to a recent update in the GeoDataFrame function `_geodataframe_constructor_with_fallback()` (see [here](https://github.com/geopandas/geopandas/commit/dc66966bbdd24b20ba8b60bb4ca8dad3a1e7c84b#diff-2bf1533512765e9a8c8ca4992b8bc2828c4f5567d9a853f160f1dbd0ea473c20L54)), where instead of the hardcoded `GeoDataFrame` (line 54), a class instance `cls` is passed to the function and implicitly initialized (line 2026). This means we cannot pass `self`, but instead need to explicitly pass and call `GeoDataFrame` to prevent initializing a trackintel class. The latter will raise an error because the geometry link is only assigned at the very end of the `GeoDataFrame._constructor_from_mgr()` function (see [here](https://github.com/geopandas/geopandas/blob/c36eba059f61 …
=> TST: fix inheritance class type error
